- name: Copy and Apply Kubernetes YAML
  hosts: 192.168.137.135  # Replace with the actual IP address of your host
  gather_facts: false
  become: true
 
  tasks:
    - name: Copy test.yaml to remote host
      copy:
        src: k8s-deply.yaml  # Replace with the actual path to your test.yaml file
        dest: k8s-deply.yaml  # Replace with the actual destination path
        mode: 0644
 
    - name: Copy your-secret-file.yaml to remote host
      copy:
        src: secret.yaml
        dest: secret.yaml  # Replace with the actual destination path
        mode: 0645
 
    - name: Apply test.yaml using kubectl
      command: "kubectl apply -f k8s-deply.yaml"
 
    - name: Apply your-secret-file.yaml using kubectl
      command: "kubectl apply -f secret.yaml"
